### PR TITLE
Update next image-config path

### LINKED ISSUE #298: next image config moved in v12.1.1+
## 🐛 Bug Report

image config import moved in next: 
https://github.com/vercel/next.js/pull/34677/files
[packages/next/shared/lib/image-config.ts](https://github.com/vercel/next.js/pull/34677/files#diff-4a94041e82272cf6fd6703f0508494a02f73a25f6a8498271278691b5e478052)

### PR DESCRIPTION
**Pull request by paul-pro**
## What kind of change does this PR introduce?

Fixes #298

## What is the current behaviour?

#298, currently resulting in
```
Test suite failed to run

    Cannot find module 'next/dist/server/image-config' from 'node_modules/next-page-tester/dist/utils.js'
```

## What is the new behaviour?

Tests run

## Does this PR introduce a breaking change?

No

## Please check if the PR fulfills these requirements:

- [n/a] Tests for the changes have been added
- [n/a] Docs have been added / updated

### CODE REVIEW

**Comment by toomuchdesign** [comment]
Hi @paul-pro, thanks for the PR. There are few points to be addressed yet:
- A formatting issue with Prettier (see CI)
- `next` peer and dev dependencies updated to the first relevant Next version
- Update compatibility table [in docs](https://github.com/next-page-tester/next-page-tester#nextjs-versions-support)

**Comment by paul-pro** [comment]
Looks like this change was released in the [next v12.1.1](https://github.com/vercel/next.js/releases/tag/v12.1.1). I'll do changes recommended by @toomuchdesign later today

**Comment by paul-pro** [comment]
@toomuchdesign, should compatibility docs be updated like
```md
| v0.31.0 +          | v12.1.0 +          |         |
| v0.32.0 +          | v12.1.1 +          |         |
```

or
```md
| v0.31.0            | v12.1.0            |         |
| v0.32.0 +          | v12.1.1 +          |         |
```

**Comment by paul-pro** [comment]
@toomuchdesign @jasonwilliams I've updated lock file again, hopefully last time

**Review by jasonwilliams — APPROVED** [review]

**Comment by paul-pro** [comment]
@toomuchdesign @jasonwilliams are we good to merge and release a new version?

**Pull request merged**
