### PR TITLE
Next v12 compatibility

### PR DESCRIPTION
**Pull request by jasonwilliams**
## What kind of change does this PR introduce?

Compatibility with next v12

There were 2 type issues, one was this:
https://github.com/vercel/next.js/pull/28646
Which needed defaultGetInitialProps to be added.

The other resolved itself by having [useMaybeDeferContent removed](https://github.com/vercel/next.js/pull/34506).

How to test this PR:
- You will need to be on node v16+
- You will need to be on Next v12+
- `npm i --save-dev next-page-tester/next-page-tester#pull/294/head`
- Set `__NEXT_TEST_MODE=jest` env

### CODE REVIEW

**Comment by jasonwilliams** [comment]
So the plan is to try and make this work with vitest instead of Jest.
This does, however, mean changing to use import() instead of require here: https://github.com/next-page-tester/next-page-tester/blob/master/src/loadFile.ts#L18

Which means `await` changes all over the place. Any help would be useful

**Comment by jasonwilliams** [comment]
Funnily enough I don’t get the segmentation fault errors when switching to dynamic import instead of require (for load file). So this is good news. But the tests do fail, so will need to see what’s going on there

**Comment by jasonwilliams** [comment]
Help is needed to run these tests and try to fix the failing ones. I think using import can help prevent the require issues. If not we may have to just move to vitest completely.

**Comment by toomuchdesign** [comment]
Hi @jasonwilliams! If the one running here is the last version, I can see a segmentation error [on Babel compilation](https://github.com/next-page-tester/next-page-tester/runs/5338028515?check_suite_focus=true#step:4:43).

**Comment by jasonwilliams** [comment]
The hanging tests have (kinda) been fixed.
I noticed this:
https://github.com/vercel/next.js/blob/canary/packages/next/server/config.ts#L644-L648

If you set the env var `__NEXT_TEST_MODE ` to `jest` before running the tests they will now all pass.

As a "quick fix" we could just do this and call it a day, but we would end up stuck with jest. That being said we may not have any other choice. I can take a look at vitest but if vitest doesn't work we have a path forward

**Comment by jasonwilliams** [comment]
Forcing __NEXT_TEST_MODE to be 'jest' would fix this PR for all those who use Jest as a test runner. But i don't know the effects for Mocha etc..

**Comment by toomuchdesign** [comment]
Ehi @jasonwilliams, I'll answer here to the question you asked privately about using [Jest's `isolateModules` ](https://jestjs.io/docs/jest-object#jestisolatemodulesfn)to feed the discussion. That was introduced to simulate Next.js server and client renders in a single testing environment. It turned out to be quite necessary to any non-basic Next setup.

You can read more about it [here](https://github.com/next-page-tester/next-page-tester/blob/master/docs/a-note-about-client-and-server-renders.md).

**Pull request closed without merging**
